#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift File.expand_path('../lib', __dir__)
require_relative '../lib/fs2md'

begin
  Fs2md::Cli.start
rescue Interrupt
  puts "\nbye bye..."
end
